# Generated by Django 3.1.7 on 2021-10-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminusers',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
